### ISSUE TITLE
Opening other documents

### ISSUE THREAD

**Issue by KelVergara** [Floydv149/bibleLinkerPro#12]
Though I've had a github account for a bit I'm still really new to using it, so if I'm breaking rules or etiquette by asking this here please let me know. But in my newb-ness I couldn't find anywhere else to ask this question. 

So I figured out how the library's linking works after installing this plugin and using it. I even was able to get it to open other publicly available documents by using the share link on the website and copying the address past the "finder?" section (and removing the "share" part).

But what I'm still confused by, and if any of you know please let me know, is how to link to other documents in the jwlibrary that are ***not*** publicly available. Like my public talk outline has a link to S-141. I have that and would like to link it so that I can click the link to open it.

I use obsidian in the left 3/4 of my screen and jwlibrary inthe right 1/4 and am planning on using this for my next public talk bc it's amazing. I can't thank you enough for this plugin. It's amazing.

PS, I'm going to put it in its own entry but I found a glitch that I don't think is your fault but a limit in what's been programmed into jwlibrary. But you might be able to address it in the plugin documentation itself.

**Comment by Juilio** [comment]
The GitHub Project JWMerger has a more ore less comlete list of the documents. But i use the share Link in the Libary. I find It easier that was. To this Moment I havent found an Automatic way Like BibleLinker for other documents...
I hope this helps, even though my english isnt good and i dont know much from programming.

**Comment by KelVergara** [comment]
> The GitHub Project JWMerger has a more ore less comlete list of the documents. But i use the share Link in the Libary. I find It easier that was. To this Moment I havent found an Automatic way Like BibleLinker for other documents... I hope this helps, even though my english isnt good and i dont know much from programming.

I tried to use the share link but it didn't work.

**Comment by Floydv149** [comment]
Interesting question!

If you use the share link option you can get a link like this: https://www.jw.org/finder?srcid=jwlshare&wtlocale=O&prefer=lang&docid=1016419

You just need to convert it to the following format to enable it to open the document in JW Library:
jwlibrary:///finder?docid=1016419

That should work for every document, if it is downloaded onto your JW Library app.
