### ISSUE TITLE
Add pt-br language

### ISSUE THREAD

**Issue by gutembergmaciel** [Floydv149/bibleLinkerPro#5]
Hello, my name is Gutemberg Maciel.
I'm from Brazil and I really liked your plugin.
However, for me to actually use it, I need the translation (including the abbreviations and names of the books) to Brazilian Portuguese.
With the little knowledge, I included the translations in your code.
I kindly ask you to evaluate and, if possible, accept the inclusion and update for all with the pt-br language.
Tanks

**Comment by Floydv149** [comment]
Hello, Gutemberg Maciel!
Thank you for your interest in my plugin and for adding the Brazilian Portugese language to my plugin.
I plan to add your code as soon as possible, whilst preparing a big update for my plugin.

**Comment by gutembergmaciel** [comment]
Wow! Thanks for the feedback.
I even made a copy and apply on my Obsidian (temporarily) this week - I even had to add more lines of code for language selection.

I'm glad there's an update coming out, I'm looking forward to it. Do you have a release date?

Taking advantage, I was researching a way to include the content of the biblical text (scraping it from the Bible online 🤔) as a quote. Can you give a spoiler if there will be this feature in the new update?

One last question, are you a Jehovah's Witness?

Thanks for your attention,

Gutemberg Maciel


________________________________
De: Floydv ***@***.***>
Enviado: Sunday, April 14, 2024 10:58:31 AM
Para: Floydv149/bibleLinkerPro ***@***.***>
Cc: Gutemberg Maciel ***@***.***>; Author ***@***.***>
Assunto: Re: [Floydv149/bibleLinkerPro] Add pt-br language (Issue #5)


Hello, Gutemberg Maciel!
Thank you for your interest in my plugin and for adding the Brazilian Portugese language to my plugin.
I plan to add your code as soon as possible, whilst preparing a big update for my plugin.

**Comment by Floydv149** [comment]
Well I have good news for you, @gutembergmaciel. The update is now live and adds your language alongside French thanks to another contributer.

I like your idea of including the content of the biblical text, but I am not sure if I will be adding that in the near future, as that isn't my field of expertise either, and will take a lot of time to figure out. What I am working on, is a feature to select a whole text with biblical texts in it, and then convert those texts to links.

And yes, I am one of Jehovah's Witnesses.

Thank you for translating my plugin to your language, and enjoy!

Floydv149
