### ISSUE TITLE
Adding the german bible to the plugin

### ISSUE THREAD

**Issue by Juilio** [Floydv149/bibleLinkerPro#7]
Hello Floydv149,

i am a Jehovahs Witnesses from germany. You made an really nice plugin for obsidian. I made a new fork from your code and tried to add german to the functional languages. I hope I did everything right. Could you please review my code and add it into the normal version if you have time.

Sorry for my bad english. I hope you understand my message.

With best regards
Joel Chemnitz from Germany

**Comment by Floydv149** [comment]
Hello @Juilio 

I am also one of Jehovah's Witnesses, from Belgium. Thank you very much for translating my plugin to support your language.
German has now been added to the plugin. You can install it by updating the plugin.

Best regards
Floydv149

PS: Your English is just fine, I understood it 😉
